version = 1

test_patterns = ["**/__tests__/**"]

exclude_patterns = ["*/examples/**"]

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  environment = [
    "nodejs",
    "jest"
  ]
  plugins = ["react"]
  dialect = "typescript"
  style_guide = "standard"
