version = 1

test_patterns = [
    "*/test/**",
    "**/__tests/**"
]

exclude_patterns = [
    "dist/**",
    "build/**"
]

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  environment = [
    "browser",
    "jest"
  ]
  plugins = ["react"]
  style_guide = "airbnb"
  dialect = "typescript"
